### ISSUE TITLE
Allow focus on AWS

### ISSUE THREAD

**Issue by lanzanasto** [simon04/eaws-bulletin-map#11]
We would like to integrate the map on Lawinen.at (and replace the current map). Therefore we would like to zoom to Austria. Can we add the region to focus on as an URL parameter? Maybe it can be flexible so we can choose between country (AT), region (AT-07) or micro-region (AT-07-01).

**Comment by simon04** [comment]
For Austria: `bbox=9.47996951665,46.4318173285,16.9796667823,49.0390742051`
