### ISSUE TITLE
No elevation dependency in Styria

### ISSUE THREAD

**Issue by lanzanasto** [simon04/eaws-bulletin-map#14]
Today (10.12.2024) the danger rating map on Avalanche.report looks different than this map for Styria. Danger Level 2 in upper regions (above 2000m) is not shown.

![image](https://github.com/user-attachments/assets/4feddd8f-07ff-4156-81e1-d50122b8a9e6)

![image](https://github.com/user-attachments/assets/f7138451-d763-4ad0-a7b0-a65807ff08be)

**Comment by simon04** [comment]
The relevant threshold change https://gitlab.com/eaws/eaws-regions/-/commit/6e51fd9264882eb1ca47100527b87da4b99e3ade had not been deployed to https://static.avalanche.report/eaws-regions.pmtiles (last-modified
	Tue, 02 Apr 2024 19:30:09 GMT). Fixed by building https://gitlab.com/eaws/eaws-regions/-/jobs/8652805380 and copying eaws-regions.pmtiles to https://static.avalanche.report/eaws-regions.pmtiles.
