### ISSUE TITLE
Color regions without danger level

### ISSUE THREAD

**Issue by lanzanasto** [simon04/eaws-bulletin-map#5]
If a region is available in EAWS, but we do not have a danger level for it (like for IT), color the area somehow.
We thought about grey, but grey is the standard color for "no information". Can we use a light blue?

**Comment by simon04** [comment]
![2023-09-01-092343](https://github.com/simon04/eaws-bulletin-map/assets/782446/606171ed-88e0-4aeb-917b-f091e862bfc1)

**Comment by lanzanasto** [comment]
Very nice!
